marker_size: 0.1188
delta_width_qr_center: 0.3267
delta_height_qr_center: 0.2079
delta_width_circles: 0.297
delta_height_circles: 0.2376
circle_radius: 0.7128
aruco_dictionary: DICT_6X6_50
marker_ids:
  top_left: 1
  top_right: 2
  bottom_right: 3
  bottom_left: 4
