"""
visualization/sequence.py

Renders an animated GIF stitching M2's overlay visualization (see
visualization.overlay) across a sampled subset of frames in the
sequence, so a person can see AT A GLANCE whether alignment quality
holds steady over time or drifts -- something a single "headline frame"
snapshot (what every other visualization in this package is anchored to)
can't show.

Opt-in and comparatively expensive: each sampled frame re-runs the full
M2 pipeline (projection, edge extraction, Canny, distance transform), so
this is never generated by default -- only when explicitly requested via
app.cli's --sequence-gif flag, with a frame budget capped by
--sequence-max-frames to keep runtime bounded regardless of how long the
input sequence is.

Uses Pillow for GIF encoding -- already a hard dependency of matplotlib
(which this project already depends on), so this doesn't add a new
top-level dependency.
"""

from __future__ import annotations

from io import BytesIO
from typing import Optional

import numpy as np
import cv2
from PIL import Image

from evaluation.edge_alignment import evaluate_edge_alignment
from visualization.overlay import render_overlay_from_result


_DEFAULT_MAX_FRAMES = 16
_DEFAULT_FPS = 4
_BANNER_BG_BGR = (23, 17, 13)   # matches report --bg (#0D1117) in BGR
_BANNER_TEXT_BGR = (243, 237, 230)  # matches report --text-primary (#E6EDF3) in BGR


def select_frame_indices(num_frames: int, max_frames: int) -> list[int]:
    """Evenly sample up to max_frames indices across [0, num_frames),
    always including the first and last frame so the animation covers
    the full sequence rather than clustering around wherever np.linspace
    happens to land."""
    if num_frames <= 0:
        return []
    if num_frames <= max_frames:
        return list(range(num_frames))
    return sorted(set(np.linspace(0, num_frames - 1, max_frames).round().astype(int).tolist()))


def _annotate(frame_bgr: np.ndarray, text: str) -> np.ndarray:
    """Draw a small dark banner + text in the top-left corner using
    OpenCV's built-in Hershey font -- no truetype font file dependency,
    unlike PIL's ImageDraw with a custom font."""
    out = frame_bgr.copy()
    (tw, th), baseline = cv2.getTextSize(text, cv2.FONT_HERSHEY_SIMPLEX, 0.5, 1)
    cv2.rectangle(out, (0, 0), (tw + 12, th + baseline + 10), _BANNER_BG_BGR, -1)
    cv2.putText(out, text, (6, th + 6), cv2.FONT_HERSHEY_SIMPLEX, 0.5, _BANNER_TEXT_BGR, 1, cv2.LINE_AA)
    return out


def render_sequence_gif(
    dataset,
    lidar_spec,
    edge_kwargs: Optional[dict] = None,
    frame_indices: Optional[list[int]] = None,
    max_frames: int = _DEFAULT_MAX_FRAMES,
    fps: int = _DEFAULT_FPS,
) -> Optional[bytes]:
    """
    Render an animated GIF: for each sampled frame, run M2 and draw the
    same per-point GOOD/WARNING/BAD overlay visualization.overlay already
    produces for the single headline frame, annotate it with the frame
    index/mean error/classification, and stitch the results into one
    looping GIF.

    frame_indices: explicit frames to render, bypassing sampling. If
    None, evenly samples up to max_frames indices via
    select_frame_indices.

    Returns None if the dataset has no frames, or if every sampled frame
    FAILed M2 (nothing to animate).
    """
    edge_kwargs = edge_kwargs or {}
    n = len(dataset.frames)
    if n == 0:
        return None

    indices = frame_indices if frame_indices is not None else select_frame_indices(n, max_frames)

    pil_frames = []
    for idx in indices:
        sf = dataset.frames[idx]
        image = sf.camera_frame.load()
        points = sf.lidar_frame.load()
        result = evaluate_edge_alignment(
            image=image, points_lidar=points, T_CL=dataset.extrinsic.T_CL,
            camera=dataset.camera, lidar_spec=lidar_spec, **edge_kwargs,
        )
        overlay_bgr = render_overlay_from_result(image, result)
        if overlay_bgr is None:
            continue  # this frame FAILed M2 -- skip rather than show a blank/misleading frame
        mean_label = f"{result.mean_px:.2f}px" if np.isfinite(result.mean_px) else "n/a"
        label = f"frame {idx} | mean {mean_label} | {result.classification}"
        annotated = _annotate(overlay_bgr, label)
        rgb = cv2.cvtColor(annotated, cv2.COLOR_BGR2RGB)
        pil_frames.append(Image.fromarray(rgb))

    if not pil_frames:
        return None

    buf = BytesIO()
    duration_ms = int(1000 / max(fps, 1))
    pil_frames[0].save(
        buf, format="GIF", save_all=True, append_images=pil_frames[1:],
        duration=duration_ms, loop=0, optimize=True,
    )
    return buf.getvalue()
